### ISSUE TITLE
Version check error(Blender 3.4)

### ISSUE THREAD

**Issue by someoneetc** [Moguri/blend2bam#75]
Hello,

I have recently encountered a small problem related with the function **in_blender_28**(defined in **blender_script_common.py**, line 40).
The function performs the following check:

`return version[0] >= 2 and version[1] >= 80`

which obviously fails with blender 3.4 causing the method Object.select() to be called instead of Object.select_set().

I have fixed my copy of blend2bam by trivially replacing the above line with the following:

`(version[0] > 2) or (version[0] == 2 and version[1] >= 80)`

Obviously, it's a minor issue which anybody familiar with Python could fix autonomously but, nonetheless, I thought to signal this.

**Comment by rdb** [comment]
It should probably just be something like `version >= (2, 80)`

**Comment by Moguri** [comment]
This was already fixed in v0.20. Are you using an older version?

**Comment by rdb** [comment]
I still see the erroneous check in the latest master version of that file.

**Comment by Moguri** [comment]
I should have paid closer attention to the filename in the post (`blender_scrip_common.py`); I was thinking about the similar check in `blenderutils.py`. I have copied the already updated logic from `blenderutils.py` to `blender_script_common.py`.
